### ISSUE TITLE
Would love an example with env variables

### ISSUE THREAD

**Issue by nikitavoloboev** [ritmillio/expo-starter-kit#1]
I asked this here too: https://github.com/ivopr/tamagui-expo/issues/34#issuecomment-1576829077

Which is my current template I am using.

This template does look interesting though, I would just love perhaps an example of how env variables can be integrated nicely in React Native code.

**Comment by ritmillio** [comment]
Hi, I will put this on the roadmap and will figure out a nice way to handle env variables in rn-expo. :) If you have any suggestions in the meantime feel free to comment it under this discussion or open a pr!

**Comment by ritmillio** [comment]
Hello @nikitavoloboev. I am slower a little bit on delivering features, but I just finished your request of loading ENV variables in a simple way on this branch : https://github.com/ritmillio/expo-starter-kit/tree/env-variables --> and merged into main. Now you only need to create a .env file in the root folder -> define your env variables -> wherever you need to use env vars you can import following the example below.

f.x.: 

`import ENV from 'src/utils/env-loader';
 console.log('ENV: ', ENV.API_KEY_TEST);`

I hope this solution will satisfy the easiness of using env variables. :)
