### ISSUE TITLE
Add Login Screen/ Register modal.

### ISSUE THREAD

**Issue by kewinzaq1** [ritmillio/expo-starter-kit#12]
@ritmillio Hi Could I take care of this?

**Comment by ritmillio** [comment]
Hi, if you can take care of this It would be awesome! Currently working on animated splash screen which could rise some conflict in the main layout file with the login/reg but We can solve the conflitcs later! Also there is no design, keep it simple and clean. Please If you want to take over this or any other screen/feature It would be nice to create a draft pull request so I can see if someone is working on something.

**Comment by kewinzaq1** [comment]
@ritmillio Hi what do you think about this? https://github.com/ritmillio/expo-starter-kit/pull/13

**Comment by ritmillio** [comment]
Hey @kewinzaq1 , I will review it during the weekend and get back to you asap. Thanks in advance to your contribution!
